-- One aggregate-product reconciliation receipt per registered source record.
-- Ordered component arrays preserve source identity; no sample/person columns exist.
CREATE TABLE IF NOT EXISTS lr_y1_primary_motif_loci (
    product_run_id String,
    release LowCardinality(String),
    cohort LowCardinality(String),
    reference_genome LowCardinality(String),
    chrom LowCardinality(String),
    primary_run_id String,
    primary_task_id String,
    primary_attempt_id String,
    source_variant_id String,
    canonical_locus_id String,
    source_position UInt32,
    source_uri String,
    source_generation String,
    source_size_bytes UInt64,
    source_md5_base64 String,
    source_index_uri String,
    source_index_generation String,
    source_index_size_bytes UInt64,
    source_index_md5_base64 String,
    source_record_sha256 FixedString(64),
    genotype_content_sha256 Nullable(FixedString(64)),
    component_starts0 Array(UInt32),
    component_ends0 Array(UInt32),
    component_motifs Array(String),
    component_digest FixedString(64),
    primary_component_index UInt16,
    primary_motif String,
    selection_basis LowCardinality(String),
    biological_role Nullable(String),
    catalog_id String,
    catalog_digest Nullable(FixedString(64)),
    registry_digest FixedString(64),
    registry_approval_state LowCardinality(String),
    metric LowCardinality(String),
    algorithm_version String,
    algorithm_sha256 FixedString(64),
    anchor_rule LowCardinality(String),
    anchor_base FixedString(1),
    trid_envelope_start0 UInt32,
    trid_envelope_end0 UInt32,
    ref_with_anchor_bytes UInt32,
    represented_ref_bytes UInt32,
    alts_checked UInt32,
    represented_sequence_bytes UInt64,
    stratum_count UInt16,
    bin_count UInt32,
    overall_an UInt32,
    overall_alt_ac UInt64,
    overall_ref_copies UInt32,
    status LowCardinality(String),
    reason_code Nullable(String),
    allele_receipt_sha256 FixedString(64),
    serialized_bytes UInt64
) ENGINE = MergeTree()
PARTITION BY (release, cohort, reference_genome, chrom, product_run_id)
ORDER BY (product_run_id, chrom, source_position, source_variant_id);
