-- Optional Phase 7 product ledger. This DDL is intentionally not part of the
-- frozen Y1 v5 initializer; a future product initializer/finalizer must attest it
-- independently and accept only REVIEWED registry receipts.
CREATE TABLE IF NOT EXISTS lr_y1_primary_motif_runs (
    product_run_id String,
    revision UInt64,
    state LowCardinality(String),
    release LowCardinality(String),
    cohort LowCardinality(String),
    reference_genome LowCardinality(String),
    chrom LowCardinality(String),
    primary_database String,
    primary_run_id String,
    registry_digest FixedString(64),
    registry_approval_state LowCardinality(String),
    metric LowCardinality(String),
    algorithm_version String,
    algorithm_sha256 FixedString(64),
    executable_revision String,
    executable_sha256 FixedString(64),
    anchor_rule LowCardinality(String),
    source_inventory_sha256 FixedString(64),
    max_alt_identities UInt32,
    max_represented_sequence_bytes UInt64,
    max_producer_bins UInt32,
    max_source_divisions UInt16,
    max_genotype_pairs_per_stratum UInt32,
    max_genotype_cells_per_stratum UInt32,
    max_serialized_aggregate_bytes UInt64,
    bounds_status LowCardinality(String),
    metadata_run_id Nullable(String),
    accepted_metadata_receipt_sha256 Nullable(FixedString(64)),
    metadata_manifest_sha256 Nullable(FixedString(64)),
    header_roster_sha256 Nullable(FixedString(64)),
    header_mapping_sha256 Nullable(FixedString(64)),
    locus_rows UInt64,
    bin_rows UInt64,
    genotype_pair_rows UInt64,
    genotype_margin_rows UInt64,
    called_diploid_people UInt64,
    partial_diploid_people UInt64,
    no_call_people UInt64,
    non_diploid_people UInt64,
    serialized_bytes UInt64,
    locus_content_sha256 FixedString(64),
    bin_content_sha256 FixedString(64),
    genotype_pair_content_sha256 Nullable(FixedString(64)),
    genotype_margin_content_sha256 Nullable(FixedString(64)),
    receipt_sha256 FixedString(64),
    created_at DateTime64(3, 'UTC'),
    updated_at DateTime64(3, 'UTC'),
    operator_identity String,
    message String
) ENGINE = ReplacingMergeTree(revision)
ORDER BY (release, cohort, reference_genome, chrom, product_run_id);
