CREATE TABLE IF NOT EXISTS lr_y1_load_runs (
    run_id String,
    revision UInt64,
    state LowCardinality(String),
    load_scope LowCardinality(String),
    release LowCardinality(String),
    cohort LowCardinality(String),
    reference_genome LowCardinality(String),
    chrom LowCardinality(String),
    interval_start UInt32,
    interval_end UInt32,
    source_uri String,
    source_generation String,
    source_checksum_algorithm LowCardinality(String),
    source_checksum String,
    source_index_uri String,
    source_index_generation String,
    source_index_checksum String,
    schema_version UInt16,
    loader_version String,
    expected_tasks UInt32,
    expected_source_records UInt64,
    summary_rows UInt64,
    allele_rows UInt64,
    frequency_rows UInt64,
    carrier_rows UInt64,
    rejected_records UInt64,
    created_at_ms UInt64,
    updated_at_ms UInt64,
    message String
) ENGINE = ReplacingMergeTree(revision)
ORDER BY run_id;
