CREATE TABLE IF NOT EXISTS lr_y1_alleles_staging (
    run_id String,
    task_id String,
    attempt_id String,
    release LowCardinality(String),
    cohort LowCardinality(String),
    reference_genome LowCardinality(String),
    chrom LowCardinality(String),
    position UInt32,
    reference_end UInt32,
    xpos UInt64,
    source_variant_id String,
    alt_index UInt16,
    ref_allele String,
    alt String,
    allele_type Nullable(String),
    qual Nullable(Float64),
    filters Array(String),
    ac UInt32,
    an UInt32,
    af Float64,
    allele_length Int32,
    length_provenance LowCardinality(String),
    rsids Array(String),
    cadd_phred Nullable(Float64),
    phylop Nullable(Float64),
    major_consequence Nullable(String),
    short_read_match_id Nullable(String),
    short_read_match_type Nullable(String),
    short_read_match_source Nullable(String)
) ENGINE = MergeTree()
PARTITION BY run_id
ORDER BY (run_id, task_id, attempt_id, chrom, position, source_variant_id, alt_index);
