CREATE TABLE IF NOT EXISTS lr_y1_metadata_runs (
    metadata_run_id String,
    revision UInt64,
    state LowCardinality(String),
    release LowCardinality(String),
    cohort LowCardinality(String),
    reference_genome LowCardinality(String),
    source_manifest_id String,
    source_manifest_sha256 FixedString(64),
    source_manifest_json String,
    expected_roster_rows UInt16,
    observed_roster_rows UInt16,
    primary_source_rows UInt16,
    primary_roster_overlap UInt16,
    supplemental_source_rows UInt16,
    supplemental_unique_samples UInt16,
    output_rows UInt16,
    supplemental_assignments UInt16,
    primary_retained_conflicts UInt16,
    exact_supplemental_duplicates UInt16,
    audit_rows UInt16,
    publisher_identity String,
    report_uri String,
    report_sha256 String,
    created_at_ms UInt64,
    completed_at_ms UInt64,
    failure_reason String
) ENGINE = ReplacingMergeTree(revision)
ORDER BY metadata_run_id;
