CREATE TABLE IF NOT EXISTS lr_y1_ancillary_task_attempts (
    ancillary_run_id String,
    modality LowCardinality(String),
    chrom LowCardinality(String),
    task_id String,
    attempt_id String,
    lease_id String,
    sample_id LowCardinality(String),
    data_layer LowCardinality(String),
    source_haplotype Nullable(UInt8),
    manifest_entry_id String,
    source_object_slot LowCardinality(String),
    source_uri String,
    source_generation String,
    source_size_bytes UInt64,
    source_checksum_algorithm LowCardinality(String),
    source_checksum String,
    interval_start UInt32,
    interval_end UInt32,
    state LowCardinality(String),
    source_rows UInt64,
    staged_rows UInt64,
    reject_rows UInt64,
    key_hash FixedString(64),
    content_hash FixedString(64),
    error Nullable(String),
    created_at DateTime64(3, 'UTC'),
    revision UInt64
) ENGINE = ReplacingMergeTree(revision)
ORDER BY (ancillary_run_id, modality, chrom, task_id, attempt_id);
